### ISSUE TITLE
请问如何运行？

### ISSUE THREAD

**Issue by willzoe** [duanshengliu/End-to-end-for-chinese-plate-recognition#1]
我在win10下用anaconda配置了环境，请问如何运行程序呢？

**Comment by duanshengliu** [comment]
确认环境是否如下：环境：python:3.6, tensorflow:1.15.2, opencv: 4.1.0.25，再运行UI.py即可







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 上午10:46
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[duanshengliu/End-to-end-for-chinese-plate-recognition] 请问如何运行？ (#1)





 
我在win10下用anaconda配置了环境，请问如何运行程序呢？

**Comment by duanshengliu** [comment]
确认环境是否如下：环境：python:3.6, tensorflow:1.15.2, opencv: 4.1.0.25，再运行UI.py即可

**Comment by willzoe** [comment]
可以运行了 谢谢~
