### ISSUE TITLE
请问支持绿牌和黄牌吗？

### ISSUE THREAD

**Issue by Mrzhaopy** [duanshengliu/End-to-end-for-chinese-plate-recognition#11]
作者您好：
       我在使用的时候发现unet对蓝牌分割效果较好，对绿牌分割效果较差，以及自己标注绿牌，黄牌使用unet进行训练吗，车牌矫正代码是否支持其他颜色车牌？

**Comment by duanshengliu** [comment]
我训练集只有蓝牌的，其他牌数据集没有添加，可能是你绿牌的数据集比蓝牌的少吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 中午1:30
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[duanshengliu/End-to-end-for-chinese-plate-recognition] 请问支持绿牌和黄牌吗？ (#11)





 
作者您好：
 我在使用的时候发现unet对蓝牌分割效果较好，对绿牌分割效果较差，以及自己标注绿牌，黄牌使用unet进行训练吗，车牌矫正代码是否支持其他颜色车牌？

**Comment by Mrzhaopy** [comment]
我的数据绿牌较多，所以想在您的基础上训练自己的数据，opencv那块不太熟，所以想问下opencv矫正那块对颜色没有要求吧

**Comment by duanshengliu** [comment]
不影响，我unet部分是1500张左右&nbsp;



---原始邮件---
发件人: "Mrzhaopy"<notifications@github.com&gt;
发送时间: 2020年12月28日(周一) 中午1:37
收件人: "duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"duanshengliu"<1069033158@qq.com&gt;;
主题: Re: [duanshengliu/End-to-end-for-chinese-plate-recognition] 请问支持绿牌和黄牌吗？ (#11)




 
我的数据绿牌较多，所以想在您的基础上训练自己的数据，opencv那块不太熟，所以想问下opencv矫正那块对颜色没有要求吧

**Comment by Mrzhaopy** [comment]
好的，非常感谢您的回复

**Comment by daijie1223** [comment]
> 我的数据绿牌较多，所以想在您的基础上训练自己的数据，opencv那块不太熟，所以想问下opencv矫正那块对颜色没有要求吧
可以提供你的数据集吗？或者我们可以交换。我有5w+的蓝牌，3w+的绿牌。q:10413577014

**Comment by fusinjay** [comment]
> 作者您好： 我在使用的时候发现unet对蓝牌分割效果较好，对绿牌分割效果较差，以及自己标注绿牌，黄牌使用unet进行训练吗，车牌矫正代码是否支持其他颜色车牌？

您好，请问一下你这边别的车牌的实现了吗？
