### ISSUE TITLE
为什么无法下载？

### ISSUE THREAD

**Issue by chr0929** [duanshengliu/End-to-end-for-chinese-plate-recognition#13]
下载后只有14M，解压报错

**Comment by duanshengliu** [comment]
github下载不了的话使用码云下载吧



---原始邮件---
发件人: "chr0929"<notifications@github.com&gt;
发送时间: 2021年2月18日(周四) 晚上10:45
收件人: "duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [duanshengliu/End-to-end-for-chinese-plate-recognition] 为什么无法下载？ (#13)




 
下载后只有14M，解压报错

**Comment by chr0929** [comment]
谢谢，已下载。请问有数据集吗？能不能分享一下，我的邮箱是1447826507@qq.com
