### ISSUE TITLE
cnn.h5是否失效了，打不开？

### ISSUE THREAD

**Issue by hongweiwork** [duanshengliu/End-to-end-for-chinese-plate-recognition#9]
项目中的cnn.h5文件打不开，请问是失效了还是什么原因？谢谢回复。

**Comment by duanshengliu** [comment]
&nbsp;检查一下tensorflow版本是否为1.15.2





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 下午2:27
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[duanshengliu/End-to-end-for-chinese-plate-recognition] cnn.h5是否失效了，打不开？ (#9)





 
项目中的cnn.h5文件打不开，请问是失效了还是什么原因？谢谢回复。

**Comment by hongweiwork** [comment]
您好，请问运行UI.py并选择好车牌图片点击车牌识别出现TypeError: Layout of the output array image is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels问题怎么解决，谢谢回复

**Comment by duanshengliu** [comment]
我这边貌似没有出现类似问题呢，你查查是否是opencv版本和我是否一致？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "duanshengliu/End-to-end-for-chinese-plate-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 晚上10:45
收件人:&nbsp;"duanshengliu/End-to-end-for-chinese-plate-recognition"<End-to-end-for-chinese-plate-recognition@noreply.github.com&gt;;
抄送:&nbsp;"不啻逍遥然"<1069033158@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [duanshengliu/End-to-end-for-chinese-plate-recognition] cnn.h5是否失效了，打不开？ (#9)





 
您好，请问运行UI.py并选择好车牌图片点击车牌识别出现TypeError: Layout of the output array image is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels问题怎么解决，谢谢回复
